SELECT
	C.FIRST_NAME as nome, C.last_name as sobrenome,C.CPF,C.EMAIL,C.CITY,C.STATE,
	
	P.BRAND as marca,p.price AS preco,
	COUNT(*) AS quantidade
FROM
	SALES.FUNNEL AS F
	JOIN SALES.CUSTOMERS AS C 
	ON F.CUSTOMER_ID = C.CUSTOMER_ID
	JOIN SALES.PRODUCTS AS P
	ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
	C.FIRST_NAME,last_name,
	P.BRAND,p.price ,C.CPF ,C.EMAIL,C.CITY,C.STATE

limit 10

--VEÍCULOS ADQUIRIDOS POR CLIENTE

	